/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp BTService.xml -i BTService.h -p BTServiceProxy
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "BTServiceProxy.h"

/*
 * Implementation of interface class LocalDbusServerBluetoothInterface
 */

LocalDbusServerBluetoothInterface::LocalDbusServerBluetoothInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

LocalDbusServerBluetoothInterface::~LocalDbusServerBluetoothInterface()
{
}

